cprintf('keywords', 'A short demonstration of the GSW Oceanographic Toolbox now follows.\n')
cprintf('comment', 'The following vertical profile,  from the North Pacific,  is of\n')
cprintf('comment', 'Practical Salinity,  SP,  and in situ temperature,  t,  as a function\n')
cprintf('comment', 'of pressure,  p, \n')
cprintf('text', '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 'SP = [', gsw_cv.SP_chck_cast([1, 22, 29:4:45], 1)', ']')
cprintf('text', '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 't  = [', gsw_cv.t_chck_cast([1, 22, 29:4:45], 1)', ']')
cprintf('text', '%s %7.0f  %7.0f  %7.0f  %7.0f  %7.0f  %7.0f  %7.0f %s \n' , 'p  = [', gsw_cv.p_chck_cast([1, 22, 29:4:45], 1)', ']')
cprintf('comment', 'We have shown only seven bottles from the full vertical profile.\n')
cprintf('text', ' \n')
cprintf('comment', 'We now convert Practical Salinity,  SP,  into Absolute Salinity,  SA, \n')
cprintf('comment', 'using the function "gsw.SA_from_SP", \n')
cprintf('text', 'SA = gsw.SA_from_SP(SP, p, long, lat)\n')
cprintf('text', '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 'SA = [', SA_chck_cast([1, 22, 29:4:45], 1)', ']')
cprintf('text', ' \n')
cprintf('comment', 'We now convert in situ temperature,  t,  into Conservative Temperature,  CT\n')
cprintf('comment', 'using the function "gsw.CT_from_t", \n')
cprintf('text', 'CT = gsw.CT_from_t(SA, t, p)\n')
cprintf('text', '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %7.4f %s \n' , 'CT = [', CT_chck_cast([1, 22, 29:4:45], 1)', ']')
cprintf('text', ' \n')
cprintf('keywords', 'We now plot the profile on the Absolute Salinity - Conservative Temperature diagram\n')
cprintf('comment', 'Potential density anomaly contours are shown for two different reference\n')
cprintf('comment', 'pressures; 0 dbar and 2000 dbar. These values are obtained by using the function\n')
cprintf('comment', '"gsw.rho_CT" - 1000 kg/m3,  as follows, \n')
cprintf('text', 'sigma_Theta = gsw.rho_CT(SA, CT, 0) - 1000\n')
cprintf('text', 'sigma_2 = gsw.rho_CT(SA, CT, 2000) - 1000\n')

disp('A short demonstation of the GSW Oceanographic Toolbox now follows.')
disp('The following vertical profile,  from the North Pacific,  is of')
disp('Practical Salinity,  SP,  and in situ temperature,  t,  as a function')
disp('of pressure,  p, ')
fprintf(1, '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 'SP = [', gsw_cv.SP_chck_cast([1, 22, 29:4:45], 1)', ']')
fprintf(1, '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 't  = [', gsw_cv.t_chck_cast([1, 22, 29:4:45], 1)', ']')
fprintf(1, '%s %7.0f  %7.0f  %7.0f  %7.0f  %7.0f  %7.0f  %7.0f %s \n' , 'p  = [', gsw_cv.p_chck_cast([1, 22, 29:4:45], 1)', ']')
disp('We have shown only seven bottles from the full vertical profile.')
disp(' ')
disp('We now convert Practical Salinity,  SP,  into Absolute Salinity,  SA, ')
disp('using the function "gsw.SA_from_SP", ')
disp('SA = gsw.SA_from_SP(SP, p, long, lat)')
fprintf(1, '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 'SA = [', SA_chck_cast([1, 22, 29:4:45], 1)', ']')
disp(' ')
disp('We now convert in situ temperature,  t,  into Conservative Temperature,  CT')
disp('using the function "gsw.CT_from_t", ')
disp('CT = gsw.CT_from_t(SA, t, p)')
fprintf(1, '%s %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f  %7.4f %s \n' , 'CT = [', CT_chck_cast([1, 22, 29:4:45], 1)', ']')
disp(' ')
disp('We now plot the profile on the Absolute Salinity - Conservative Temperature diagram')
disp('Potential density anomaly contours are shown for two different reference')
disp('pressures; 0 dbar and 2000 dbar. These values are obtained by using the function')
disp('"gsw.rho_CT" - 1000 kg/m3,  as follows, ')
disp('sigma_Theta = gsw.rho_CT(SA, CT, 0) - 1000')
disp('sigma_2 = gsw.rho_CT(SA, CT, 2000) - 1000')
SA_gridded = meshgrid([34:0.01:35.6], 1:301)
CT_gridded = meshgrid([0:0.1:30], 1:161)';
isopycs_0 = gsw.rho_CT(SA_gridded, CT_gridded, 0)-1000;
isopycs_2 = gsw.rho_CT(SA_gridded, CT_gridded, 2000)-1000;
figure
[c0, h0]=contour(SA_gridded, CT_gridded, isopycs_0, [21:0.5:29], 'k', 'linewidth', 0.5)
hold on
[c2, h2]=contour(SA_gridded, CT_gridded, isopycs_2, [21:0.5:40], 'r', 'linewidth', 0.5)
clabel(c0, h0, 'labelspacing', 360)
clabel(c2, h2, 'labelspacing', 240, 'color', 'r')
plot(SA_chck_cast(:, 1), CT_chck_cast(:, 1), 'b', 'linewidth', 2)
plot(SA_chck_cast([1, 22, 29:4:45], 1), CT_chck_cast([1, 22, 29:4:45], 1), 'co', 'linewidth', 2, 'Markersize', 8)
xlabel('Absolute Salinity,  S_A [g/kg]', 'fontsize', 15)
ylabel('Conservative Temperature,   {\Theta} [{\circ}C]', 'fontsize', 15)
title(['S_A - {\Theta} for a profile at (', num2str(gsw_cv.long_chck_cast(1)), ' {\circ}E,  ', num2str(gsw_cv.lat_chck_cast(1)), ' {\circ}N)'], 'fontsize', 15)
lh = plot(1:2, 1:2, 'k', 1:2, 1:2, 'r')
lh2 = legend(lh, '{\sigma^\Theta}', '{\sigma_2}', 'Location', 'southEast')
set(lh2, 'FontSize', 15)